services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,sqs,cloudwatch,lambda,dynamodb,sns
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack_data:/var/lib/localstack"
