name = "customersync-api"
compatibility_date = "2025-03-11"
main = "src/index.js"

[[d1_databases]]
binding = "DB"
database_name = "meu-db"
database_id = "8b9ce910-3da5-433e-a5c9-8100df71035a"

[[kv_namespaces]]
binding = "CACHE"
id = "2bfac58f552844a5b1f42615facc2a89"
